const destinations = [
  {
    id: 1,
    name: 'Jaipur',
    type: 'Popular',
    budget: '₹35,000 - ₹45,000',
    desc: 'Palaces, Forts',
    image: 'https://source.unsplash.com/300x200/?jaipur',
  },
  {
    id: 2,
    name: 'Goa',
    type: 'Popular',
    budget: '₹40,000 - ₹50,000',
    desc: 'Beaches, Nightlife',
    image: 'https://source.unsplash.com/300x200/?goa',
  },
  {
    id: 3,
    name: 'Agra',
    type: 'Popular',
    budget: '₹30,000 - ₹40,000',
    desc: 'Taj Mahal, History',
    image: 'https://source.unsplash.com/300x200/?agra',
  },
  {
    id: 4,
    name: 'Varanasi',
    type: 'Popular',
    budget: '₹25,000 - ₹35,000',
    desc: 'Ghats, Temples',
    image: 'https://source.unsplash.com/300x200/?varanasi',
  },
  {
    id: 5,
    name: 'Mysore',
    type: 'Popular',
    budget: '₹38,000 - ₹45,000',
    desc: 'Palace, Yoga',
    image: 'https://source.unsplash.com/300x200/?mysore',
  },
  {
    id: 6,
    name: 'Udaipur',
    type: 'Popular',
    budget: '₹45,000 - ₹55,000',
    desc: 'Lake, Palaces',
    image: 'https://source.unsplash.com/300x200/?udaipur',
  },
  {
    id: 7,
    name: 'Darjeeling',
    type: 'Popular',
    budget: '₹30,000 - ₹40,000',
    desc: 'Tea Gardens, Hills',
    image: 'https://source.unsplash.com/300x200/?darjeeling',
  },

  // Culture-Oriented Indian (6+)
  {
    id: 8,
    name: 'Khajuraho',
    type: 'Culture',
    budget: '₹25,000 - ₹35,000',
    desc: 'Temples, Sculptures',
    image: 'https://source.unsplash.com/300x200/?khajuraho',
  },
  {
    id: 9,
    name: 'Hampi',
    type: 'Culture',
    budget: '₹30,000 - ₹40,000',
    desc: 'Ruins, Temples',
    image: 'https://source.unsplash.com/300x200/?hampi',
  },
  {
    id: 10,
    name: 'Kochi',
    type: 'Culture',
    budget: '₹35,000 - ₹45,000',
    desc: 'Backwaters, History',
    image: 'https://source.unsplash.com/300x200/?kochi',
  },
  {
    id: 11,
    name: 'Pondicherry',
    type: 'Culture',
    budget: '₹28,000 - ₹35,000',
    desc: 'French Quarters, Beach',
    image: 'https://source.unsplash.com/300x200/?pondicherry',
  },
  {
    id: 12,
    name: 'Ujjain',
    type: 'Culture',
    budget: '₹20,000 - ₹30,000',
    desc: 'Temples, Heritage',
    image: 'https://source.unsplash.com/300x200/?ujjain',
  },
  {
    id: 13,
    name: 'Madurai',
    type: 'Culture',
    budget: '₹25,000 - ₹35,000',
    desc: 'Temples, History',
    image: 'https://source.unsplash.com/300x200/?madurai',
  },

  // Beach (6+)
  {
    id: 14,
    name: 'Andaman',
    type: 'Beach',
    budget: '₹60,000 - ₹70,000',
    desc: 'Scuba, Island',
    image: 'https://source.unsplash.com/300x200/?andaman',
  },
  {
    id: 15,
    name: 'Varkala',
    type: 'Beach',
    budget: '₹45,000 - ₹55,000',
    desc: 'Cliffs, Beach',
    image: 'https://source.unsplash.com/300x200/?varkala',
  },
  {
    id: 16,
    name: 'Gokarna',
    type: 'Beach',
    budget: '₹40,000 - ₹50,000',
    desc: 'Peaceful Beaches, Trek',
    image: 'https://source.unsplash.com/300x200/?gokarna',
  },
  {
    id: 17,
    name: 'Puri',
    type: 'Beach',
    budget: '₹30,000 - ₹40,000',
    desc: 'Temples, Beach',
    image: 'https://source.unsplash.com/300x200/?puri',
  },
  {
    id: 18,
    name: 'Alleppey',
    type: 'Beach',
    budget: '₹35,000 - ₹45,000',
    desc: 'Backwaters, Beach',
    image: 'https://source.unsplash.com/300x200/?alleppey',
  },
  {
    id: 19,
    name: 'Radhanagar',
    type: 'Beach',
    budget: '₹55,000 - ₹65,000',
    desc: 'Island, Beach',
    image: 'https://source.unsplash.com/300x200/?radhanagar',
  },

  // Adventure Indian (6+)
  {
    id: 20,
    name: 'Leh-Ladakh',
    type: 'Adventure',
    budget: '₹75,000 - ₹85,000',
    desc: 'Mountains, Trek',
    image: 'https://source.unsplash.com/300x200/?leh-ladakh',
  },
  {
    id: 21,
    name: 'Rishikesh',
    type: 'Adventure',
    budget: '₹20,000 - ₹30,000',
    desc: 'River Rafting, Yoga',
    image: 'https://source.unsplash.com/300x200/?rishikesh-adventure',
  },
  {
    id: 22,
    name: 'Manali',
    type: 'Adventure',
    budget: '₹45,000 - ₹55,000',
    desc: 'Hills, Trekking',
    image: 'https://source.unsplash.com/300x200/?manali',
  },
  {
    id: 23,
    name: 'Auli',
    type: 'Adventure',
    budget: '₹35,000 - ₹45,000',
    desc: 'Skiing, Mountains',
    image: 'https://source.unsplash.com/300x200/?auli',
  },
  {
    id: 24,
    name: 'Coorg',
    type: 'Adventure',
    budget: '₹30,000 - ₹40,000',
    desc: 'Trekking, Coffee Hills',
    image: 'https://source.unsplash.com/300x200/?coorg',
  },
  {
    id: 25,
    name: 'Spiti Valley',
    type: 'Adventure',
    budget: '₹50,000 - ₹60,000',
    desc: 'Mountains, Trek',
    image: 'https://source.unsplash.com/300x200/?spiti',
  },

  // International (just a few)
  {
    id: 26,
    name: 'Paris',
    type: 'Popular',
    budget: '₹95,000 - ₹1,05,000',
    desc: 'Eiffel Tower, Louvre',
    image: 'https://source.unsplash.com/300x200/?paris',
  },
  {
    id: 27,
    name: 'Kyoto',
    type: 'Culture',
    budget: '₹70,000 - ₹75,000',
    desc: 'Temples, Gardens',
    image: 'https://source.unsplash.com/300x200/?kyoto',
  },
  {
    id: 28,
    name: 'Bali',
    type: 'Beach',
    budget: '₹80,000 - ₹90,000',
    desc: 'Beaches, Surfing',
    image: 'https://source.unsplash.com/300x200/?bali',
  },
  {
    id: 29,
    name: 'New Zealand',
    type: 'Adventure',
    budget: '₹1,20,000 - ₹1,40,000',
    desc: 'Mountains, Trek',
    image: 'https://source.unsplash.com/300x200/?newzealand',
  },
];

export default destinations;
