const locationData = {
  // North India
  Delhi: {
    attractions: [
      { name: 'India Gate' },
      { name: 'Qutub Minar' },
      { name: 'Red Fort' },
      { name: 'Lotus Temple' },
      { name: 'Humayun’s Tomb' },
      { name: 'Rashtrapati Bhavan' },
      { name: 'Akshardham Temple' },
      { name: 'Chandni Chowk' },
      { name: 'Jama Masjid' },
      { name: 'National Museum' },
    ],
  },
  Agra: {
    attractions: [
      { name: 'Taj Mahal' },
      { name: 'Agra Fort' },
      { name: 'Fatehpur Sikri' },
      { name: 'Mehtab Bagh' },
      { name: 'Tomb of Itimad-ud-Daulah' },
      { name: 'Akbar’s Tomb, Sikandra' },
      { name: 'Jama Masjid Agra' },
      { name: 'Chini Ka Rauza' },
      { name: 'Mankameshwar Temple' },
      { name: 'Mariam’s Tomb' },
    ],
  },
  Jaipur: {
    attractions: [
      { name: 'Amber Fort' },
      { name: 'City Palace' },
      { name: 'Hawa Mahal' },
      { name: 'Jantar Mantar' },
      { name: 'Nahargarh Fort' },
      { name: 'Jaigarh Fort' },
      { name: 'Albert Hall Museum' },
      { name: 'Jal Mahal' },
      { name: 'Birla Mandir' },
      { name: 'Govind Dev Ji Temple' },
    ],
  },
  Varanasi: {
    attractions: [
      { name: 'Kashi Vishwanath Temple' },
      { name: 'Dashashwamedh Ghat' },
      { name: 'Manikarnika Ghat' },
      { name: 'Assi Ghat' },
      { name: 'Sarnath' },
      { name: 'Banaras Hindu University' },
      { name: 'Tulsi Manas Mandir' },
      { name: 'Bharat Mata Mandir' },
      { name: 'Ramnagar Fort' },
      { name: 'Annapurna Temple' },
    ],
  },
  Amritsar: {
    attractions: [
      { name: 'Golden Temple' },
      { name: 'Jallianwala Bagh' },
      { name: 'Wagah Border' },
      { name: 'Durgiana Temple' },
      { name: 'Partition Museum' },
      { name: 'Gobindgarh Fort' },
      { name: 'Khalsa College' },
      { name: 'Maharaja Ranjit Singh Museum' },
      { name: 'Ram Tirath Temple' },
      { name: 'Mata Lal Devi Mandir' },
    ],
  },
  Vrindavan: {
    attractions: [
      { name: 'Banke Bihari Temple' },
      { name: 'ISKCON Temple' },
      { name: 'Prem Mandir' },
      { name: 'Radha Raman Temple' },
      { name: 'Nidhivan' },
      { name: 'Rangaji Temple' },
      { name: 'Radha Vallabh Temple' },
      { name: 'Seva Kunj' },
      { name: 'Shahji Temple' },
      { name: 'Kusum Sarovar' },
    ],
  },

  // West India
  Mumbai: {
    attractions: [
      { name: 'Gateway of India' },
      { name: 'Marine Drive' },
      { name: 'Elephanta Caves' },
      { name: 'Chhatrapati Shivaji Maharaj Terminus' },
      { name: 'Juhu Beach' },
      { name: 'Siddhivinayak Temple' },
      { name: 'Haji Ali Dargah' },
      { name: 'Bandra-Worli Sea Link' },
      { name: 'Mani Bhavan' },
      { name: 'Colaba Causeway' },
    ],
  },
  Pune: {
    attractions: [
      { name: 'Shaniwar Wada' },
      { name: 'Aga Khan Palace' },
      { name: 'Sinhagad Fort' },
      { name: 'Pataleshwar Cave Temple' },
      { name: 'Parvati Hill' },
      { name: 'Osho Ashram' },
      { name: 'Raja Dinkar Kelkar Museum' },
      { name: 'Bund Garden' },
      { name: 'Pune Okayama Friendship Garden' },
      { name: 'Dagdusheth Halwai Ganpati Temple' },
    ],
  },
  Goa: {
    attractions: [
      { name: 'Baga Beach' },
      { name: 'Anjuna Beach' },
      { name: 'Basilica of Bom Jesus' },
      { name: 'Fort Aguada' },
      { name: 'Dudhsagar Falls' },
      { name: 'Se Cathedral' },
      { name: 'Chapora Fort' },
      { name: 'Colva Beach' },
      { name: 'Miramar Beach' },
      { name: 'St. Augustine Tower' },
    ],
  },

  // South India
  Bangalore: {
    attractions: [
      { name: 'Lalbagh Botanical Garden' },
      { name: 'Bangalore Palace' },
      { name: 'Cubbon Park' },
      { name: 'Vidhana Soudha' },
      { name: 'ISKCON Temple' },
      { name: 'Bannerghatta National Park' },
      { name: 'Tipu Sultan’s Summer Palace' },
      { name: 'Ulsoor Lake' },
      { name: 'Bull Temple' },
      { name: 'National Gallery of Modern Art' },
    ],
  },
  Hyderabad: {
    attractions: [
      { name: 'Charminar' },
      { name: 'Golconda Fort' },
      { name: 'Hussain Sagar Lake' },
      { name: 'Salar Jung Museum' },
      { name: 'Chowmahalla Palace' },
      { name: 'Ramoji Film City' },
      { name: 'Birla Mandir' },
      { name: 'Mecca Masjid' },
      { name: 'Nehru Zoological Park' },
      { name: 'Shilparamam' },
    ],
  },
  Chennai: {
    attractions: [
      { name: 'Marina Beach' },
      { name: 'Kapaleeshwarar Temple' },
      { name: 'Fort St. George' },
      { name: 'Santhome Cathedral' },
      { name: 'Valluvar Kottam' },
      { name: 'Guindy National Park' },
      { name: 'Government Museum' },
      { name: 'Elliot’s Beach' },
      { name: 'Arignar Anna Zoological Park' },
      { name: 'Mylapore Temple' },
    ],
  },

  // East India
  Kolkata: {
    attractions: [
      { name: 'Victoria Memorial' },
      { name: 'Howrah Bridge' },
      { name: 'Dakshineswar Kali Temple' },
      { name: 'Belur Math' },
      { name: 'Indian Museum' },
      { name: 'Marble Palace' },
      { name: 'St. Paul’s Cathedral' },
      { name: 'Eco Park' },
      { name: 'Science City' },
      { name: 'Prinsep Ghat' },
    ],
  },
  Puri: {
    attractions: [
      { name: 'Jagannath Temple' },
      { name: 'Puri Beach' },
      { name: 'Konark Sun Temple' },
      { name: 'Chilika Lake' },
      { name: 'Gundicha Temple' },
      { name: 'Raghurajpur Artist Village' },
      { name: 'Loknath Temple' },
      { name: 'Puri Museum' },
      { name: 'Atharnala Bridge' },
      { name: 'Golden Beach' },
    ],
  },

  // North-East India
  Guwahati: {
    attractions: [
      { name: 'Kamakhya Temple' },
      { name: 'Umananda Temple' },
      { name: 'Assam State Museum' },
      { name: 'Nehru Park' },
      { name: 'Basistha Ashram' },
      { name: 'Pobitora Wildlife Sanctuary' },
      { name: 'Srimanta Sankaradeva Kalakshetra' },
      { name: 'Brahmaputra Riverfront' },
      { name: 'Deepor Beel' },
      { name: 'Shilpagram' },
    ],
  },
  Shillong: {
    attractions: [
      { name: 'Elephant Falls' },
      { name: 'Shillong Peak' },
      { name: 'Ward’s Lake' },
      { name: 'Lady Hydari Park' },
      { name: 'Don Bosco Museum' },
      { name: 'Umiam Lake' },
      { name: 'Cathedral of Mary Help of Christians' },
      { name: 'Laitumkhrah Market' },
      { name: 'Sweet Falls' },
      { name: 'Air Force Museum' },
    ],
  },
};

export default locationData;
